import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
MODELS_DIR = BASE_DIR / "models"
OUTPUT_DIR = BASE_DIR / "output"
LOGS_DIR = BASE_DIR / "logs"
DATASET_DIR = BASE_DIR / "dataset"

for d in [MODELS_DIR, OUTPUT_DIR, LOGS_DIR, DATASET_DIR]:
    d.mkdir(exist_ok=True)

YOLO_MODEL = "yolov8n.pt"
CONFIDENCE_THRESHOLD = 0.5
PERSON_CLASS_ID = 0

POSE_CONFIDENCE = 0.7
POSE_TRACKING_CONFIDENCE = 0.5

# fall thresholds
FALL_ASPECT_RATIO_THRESHOLD = 0.6
FALL_BODY_MIN_WIDTH_RATIO = 0.35
FALL_LYING_TIME_THRESHOLD = 1.0
FALL_IMMOBILE_THRESHOLD = 0.6
FALL_CENTER_HEIGHT_DIFF = 0.3

# abnormal movement thresholds
FACE_ASYMMETRY_THRESHOLD = 0.15
ARM_ASYMMETRY_THRESHOLD = 0.25
BODY_TILT_THRESHOLD = 25
WALKING_UNSTABLE_THRESHOLD = 15
ABNORMAL_RESP_THRESHOLD = 0.7

RISK_ALERT_THRESHOLD = 0.7
ALERT_COOLDOWN_SECONDS = 2.5
DEBUG_MODE = True
SAVE_LOGS = True
SAVE_VIDEO_ON_ALERT = True

CAMERA_INDEX = 0
VIDEO_PATH = None

FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FPS = 30
